version: '3.8'

services:
  api:
    build: ./
    env_file:
      - ./.env
    networks:
      - cinema_network
    ports:
      - 127.0.0.1:8000:8000

networks:
  cinema_network:
    name: cinema_network
    external: True